services:
  amargosaturismo-portainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: amargosaturismo-portainer:latest
    container_name: amargosaturismo-portainer
    restart: unless-stopped
    ports:
      - "13013:80"
