CREATE TABLE IF NOT EXISTS tourism_submissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(64) NOT NULL,
  approval_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  category ENUM('gastronomia', 'hotel') NOT NULL,
  point_id VARCHAR(128) NOT NULL,
  map_focus VARCHAR(128) NOT NULL,
  name VARCHAR(255) NOT NULL,
  cnpj VARCHAR(32) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  photo_url VARCHAR(500) NOT NULL,
  instagram_url VARCHAR(500) NOT NULL DEFAULT '',
  whatsapp_url VARCHAR(500) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(64) NOT NULL DEFAULT '',
  phone_url VARCHAR(255) NOT NULL DEFAULT '',
  address_line VARCHAR(255) NOT NULL,
  days_line VARCHAR(255) NOT NULL DEFAULT '',
  hours_line VARCHAR(255) NOT NULL DEFAULT '',
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  status_line VARCHAR(255) NOT NULL DEFAULT '',
  service_line VARCHAR(255) NOT NULL DEFAULT '',
  map_query VARCHAR(500) NOT NULL DEFAULT '',
  directions_url VARCHAR(500) NOT NULL DEFAULT '',
  popup_title_color VARCHAR(32) NOT NULL DEFAULT '',
  latitude DECIMAL(10, 8) NULL,
  longitude DECIMAL(11, 8) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  approval_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tourism_submissions_public_id (public_id),
  KEY idx_tourism_submissions_status (approval_status),
  KEY idx_tourism_submissions_category (category),
  KEY idx_tourism_submissions_point (point_id)
);

CREATE TABLE IF NOT EXISTS tourism_cards (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(64) NOT NULL,
  point_id VARCHAR(128) NOT NULL,
  category ENUM('turistico', 'gastronomia', 'hotel') NOT NULL,
  name VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  image_alt VARCHAR(255) NOT NULL DEFAULT '',
  address_line VARCHAR(255) NOT NULL DEFAULT '',
  schedule_line VARCHAR(255) NOT NULL DEFAULT '',
  instagram_url VARCHAR(500) NOT NULL DEFAULT '',
  whatsapp_url VARCHAR(500) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(64) NOT NULL DEFAULT '',
  latitude DECIMAL(10, 8) NULL,
  longitude DECIMAL(11, 8) NULL,
  directions_url VARCHAR(500) NOT NULL DEFAULT '',
  marker_icon ENUM('attraction', 'heritage', 'gastronomy', 'lodging') NOT NULL DEFAULT 'attraction',
  display_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tourism_cards_public_id (public_id),
  UNIQUE KEY uk_tourism_cards_point_id (point_id),
  KEY idx_tourism_cards_category (category),
  KEY idx_tourism_cards_active_order (is_active, display_order)
);
